github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

helpers:
  "bin/helper": "github.com/paketo-buildpacks/libjvm/cmd/helper"

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/azul-zulu"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            JDK 8
  id:              jdk
  version_pattern: "^8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jdk
    version: "8"
- name:            JRE 8
  id:              jre
  version_pattern: "^8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jre
    version: "8"
- name:            JDK 11
  id:              jdk
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jdk
    version: "11"
- name:            JRE 11
  id:              jre
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jre
    version: "11"
- name:            JDK 17
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jdk
    version: "17"
- name:            JRE 17
  id:              jre
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jre
    version: "17"
- name:            JDK 21
  id:              jdk
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jdk
    version: "21"
- name:            JRE 21
  id:              jre
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jre
    version: "21"
- name:            JDK 24
  id:              jdk
  version_pattern: "24\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jdk
    version: "24"
- name:            JRE 24
  id:              jre
  version_pattern: "24\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jre
    version: "24"


# ARM64
- name:            JDK 8 ARM64
  id:              jdk
  version_pattern: "^8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jdk
    version: "8"
    arch: "arm64"
- name:            JRE 8 ARM64
  id:              jre
  version_pattern: "^8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jre
    version: "8"
    arch: "arm64"
- name:            JDK 11 ARM64
  id:              jdk
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jdk
    version: "11"
    arch: "arm64"
- name:            JRE 11 ARM64
  id:              jre
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jre
    version: "11"
    arch: "arm64"
- name:            JDK 17 ARM64
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jdk
    version: "17"
    arch: "arm64"
- name:            JRE 17 ARM64
  id:              jre
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jre
    version: "17"
    arch: "arm64"
- name:            JDK 21 ARM64
  id:              jdk
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jdk
    version: "21"
    arch: "arm64"
- name:            JRE 21 ARM64
  id:              jre
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jre
    version: "21"
    arch: "arm64"
- name:            JDK 24 ARM64
  id:              jdk
  version_pattern: "24\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jdk
    version: "24"
    arch: "arm64"
- name:            JRE 24 ARM64
  id:              jre
  version_pattern: "24\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency:main
  with:
    type:    jre
    version: "24"
    arch: "arm64"