# Copyright 2018-2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Azul Zulu implementations of JREs and JDKs"
  homepage = "https://github.com/paketo-buildpacks/azul-zulu"
  id = "paketo-buildpacks/azul-zulu"
  keywords = ["java", "jvm", "jre", "jdk"]
  name = "Paketo Buildpack for Azul Zulu"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/azul-zulu/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    default = "0"
    description = "the headroom in memory calculation"
    launch = true
    name = "BPL_JVM_HEAD_ROOM"

  [[metadata.configurations]]
    default = "35% of classes"
    description = "the number of loaded classes in memory calculation"
    launch = true
    name = "BPL_JVM_LOADED_CLASS_COUNT"

  [[metadata.configurations]]
    default = "250"
    description = "the number of threads in memory calculation"
    launch = true
    name = "BPL_JVM_THREAD_COUNT"

  [[metadata.configurations]]
    default = ""
    description = "write heap dumps on error to this path"
    launch = true
    name = "BPL_HEAP_DUMP_PATH"

  [[metadata.configurations]]
    default = "true"
    description = "enables Java Native Memory Tracking (NMT)"
    launch = true
    name = "BPL_JAVA_NMT_ENABLED"

  [[metadata.configurations]]
    default = "summary"
    description = "configure level of NMT, summary or detail"
    launch = true
    name = "BPL_JAVA_NMT_LEVEL"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Management Extensions (JMX)"
    launch = true
    name = "BPL_JMX_ENABLED"

  [[metadata.configurations]]
    default = "5000"
    description = "configure the JMX port"
    launch = true
    name = "BPL_JMX_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java remote debugging support"
    launch = true
    name = "BPL_DEBUG_ENABLED"

  [[metadata.configurations]]
    default = "8000"
    description = "configure the remote debugging port"
    launch = true
    name = "BPL_DEBUG_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "configure whether to suspend execution until a debugger has attached"
    launch = true
    name = "BPL_DEBUG_SUSPEND"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Flight Recording (JFR)"
    launch = true
    name = "BPL_JFR_ENABLED"

  [[metadata.configurations]]
    default = ""
    description = "configure custom Java Flight Recording (JFR) arguments"
    launch = true
    name = "BPL_JFR_ARGS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "enables running jlink tool to generate custom JRE"
    name = "BP_JVM_JLINK_ENABLED"

  [[metadata.configurations]]
    build = true
    default = "--no-man-pages --no-header-files --strip-debug --compress=1"
    description = "configure custom link arguments (--output must be omitted)"
    name = "BP_JVM_JLINK_ARGS"

  [[metadata.configurations]]
    build = true
    default = "21"
    description = "the Java version"
    name = "BP_JVM_VERSION"

  [[metadata.configurations]]
    build = true
    default = "JRE"
    description = "the JVM type - JDK or JRE"
    name = "BP_JVM_TYPE"

  [[metadata.configurations]]
    description = "the JVM launch flags"
    launch = true
    name = "JAVA_TOOL_OPTIONS"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:1.8.0:update502:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:1.8.0:update502:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@8.0.482?arch=amd64"
    sha256 = "5923daaf12fd0b87e60e437aaae7b2e5b257846cdb8ac15065258fb59a1da70a"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu8.96.0.19-ca-jdk8.0.502-linux_x64.tar.gz"
    version = "8.0.502"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:1.8.0:update502:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:1.8.0:update502:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@8.0.482?arch=amd64"
    sha256 = "1b8ecd86c30177937fb98ce516e28378bb7f01d0eb71b93eb5bfc3153f27cb4e"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu8.96.0.19-ca-jre8.0.502-linux_x64.tar.gz"
    version = "8.0.502"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:11.0.32:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:11.0.32:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@11.0.32?arch=amd64"
    sha256 = "d4832d97886444346ed75fd1059c68c5e38795098e3273e4a0929fe2eb2abf76"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu11.90.19-ca-jdk11.0.32-linux_x64.tar.gz"
    version = "11.0.32"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:11.0.32:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:11.0.32:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@11.0.32?arch=amd64"
    sha256 = "5011c320ad9b127785657cc80e5783ceae91a2262eedc3a9d3f717d7375443a2"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu11.90.205-ca-jre11.0.32.1-linux_x64.tar.gz"
    version = "11.0.32"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:17.0.20:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:17.0.20:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@17.0.20?arch=amd64"
    sha256 = "32c5efedf69f4a95635ea2923f6a6ee90ce6ca83df0bd43ba55dd662d5af429a"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu17.68.17-ca-jdk17.0.20-linux_x64.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:17.0.20:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:17.0.20:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@17.0.20?arch=amd64"
    sha256 = "96c6a5cbc4d0c582bb126d41e280b254db0332a93ed37ae2219debfbe4d3e73f"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu17.68.17-ca-jre17.0.20-linux_x64.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.12:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:21.0.12:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@21.0.12?arch=amd64"
    sha256 = "b1a9df12e798770d1b2db43b402a80f1e6080cff6d5d1d1fbe5c768fb4225f6a"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu21.52.15-ca-jdk21.0.12-linux_x64.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:21.0.12:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:21.0.12:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@21.0.12?arch=amd64"
    sha256 = "8e0374ffe9ff662c2f6b1872d6b48ab3859f69de11afe583af363264d24b299f"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu21.52.15-ca-jre21.0.12-linux_x64.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:25.0.4:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:25.0.4:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@25.0.4?arch=amd64"
    sha256 = "e476f5c98952cb365ca77a814dbe3c74341e71ae76d1a87d1c0a69c7d2b1b2d0"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu25.36.15-ca-jdk25.0.4-linux_x64.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:25.0.4:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:25.0.4:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@25.0.4?arch=amd64"
    sha256 = "41540814fa9d5c28d329e4e201c31ee020fc66272b01582c261c5a73d574e80e"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu25.36.15-ca-jre25.0.4-linux_x64.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:26.0.2:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:26.0.2:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@26.0.2?arch=amd64"
    sha256 = "4b7c114917aebd0fc6284fc7111245d7747a4d9603bd12d86b384b1abc9d575d"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu26.32.13-ca-jdk26.0.2-linux_x64.tar.gz"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:26.0.2:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:26.0.2:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@26.0.2?arch=amd64"
    sha256 = "742dc4a5fca3c77a5ea512ad242cdcda364631f46722c84dc4c80390b2b9cbbd"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu26.32.13-ca-jre26.0.2-linux_x64.tar.gz"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:1.8.0:update502:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:1.8.0:update502:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@8.0.482?arch=arm64"
    sha256 = "b23296caf10d0c3db054d4a58b9dd168976991472f2203335d7c4820f98c4a4e"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu8.96.0.19-ca-jdk8.0.502-linux_aarch64.tar.gz"
    version = "8.0.502"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:1.8.0:update502:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:1.8.0:update502:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@8.0.482?arch=arm64"
    sha256 = "364a61ef81f0458ef72cca3a64ebe69d685361749e5adb5ea9a07d1dbcbecfa0"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu8.96.0.19-ca-jre8.0.502-linux_aarch64.tar.gz"
    version = "8.0.502"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:11.0.32:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:11.0.32:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@11.0.32?arch=arm64"
    sha256 = "31fb32a1c9d842f96e8e79c683996e217d087b3aeac0cc6bfc39f028eb860146"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu11.90.19-ca-jdk11.0.32-linux_aarch64.tar.gz"
    version = "11.0.32"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:11.0.32:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:11.0.32:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@11.0.32?arch=arm64"
    sha256 = "eec6d90040adca3e88a417c60eaede46f59b3d59a6b1c2b1f803e6fee9166d7b"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu11.90.19-ca-jre11.0.32-linux_aarch64.tar.gz"
    version = "11.0.32"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:17.0.20:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:17.0.20:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@17.0.20?arch=arm64"
    sha256 = "46f1dc7678760d37d38699c5a5a34dea8ed451dcdf6d27890a7b61f025e7ff60"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu17.68.17-ca-jdk17.0.20-linux_aarch64.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:17.0.20:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:17.0.20:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@17.0.20?arch=arm64"
    sha256 = "dc2004d03e7a8dc82940a35433f1337303dafdbd34a06a030ce957ba38bb3a8a"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu17.68.17-ca-jre17.0.20-linux_aarch64.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.12:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:21.0.12:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@21.0.12?arch=arm64"
    sha256 = "dc7ed9ab7dfd33f2ddb1cd8311d3b00738497961a420533d81088051eac3f195"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu21.52.15-ca-jdk21.0.12-linux_aarch64.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:21.0.12:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:21.0.12:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@21.0.12?arch=arm64"
    sha256 = "8301c06f6e020d09fd30068160adc12d33728c11c03d9ace3a1087be8e84f6e2"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu21.52.15-ca-jre21.0.12-linux_aarch64.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:25.0.4:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:25.0.4:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@25.0.4?arch=arm64"
    sha256 = "ae04e25b16116ddd0f72cb387742d5122bb29c4b94f0fed08ff2bccc395f9daa"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu25.36.15-ca-jdk25.0.4-linux_aarch64.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:25.0.4:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:25.0.4:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@25.0.4?arch=arm64"
    sha256 = "94f62bbf0e0c8928dbe97d027a5b96f934d53bb56ee9c9571481d2b7003bc3d2"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu25.36.15-ca-jre25.0.4-linux_aarch64.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:26.0.2:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:26.0.2:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@26.0.2?arch=arm64"
    sha256 = "5b222fce0b7076a10ac7ae3b1009a6c2caf4f35bc4e81de72010af6750c5e146"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu26.32.13-ca-jdk26.0.2-linux_aarch64.tar.gz"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:26.0.2:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:26.0.2:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@26.0.2?arch=arm64"
    sha256 = "bc04cef6efd47e7efd87e6e3d83cd009e7bcf85ae25cb051066dcbed5fc1cba6"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu26.32.13-ca-jre26.0.2-linux_aarch64.tar.gz"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
