# Copyright 2018-2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Azul Zulu implementations of JREs and JDKs"
  homepage = "https://github.com/paketo-buildpacks/azul-zulu"
  id = "paketo-buildpacks/azul-zulu"
  keywords = ["java", "jvm", "jre", "jdk"]
  name = "Paketo Buildpack for Azul Zulu"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/azul-zulu/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    default = "0"
    description = "the headroom in memory calculation"
    launch = true
    name = "BPL_JVM_HEAD_ROOM"

  [[metadata.configurations]]
    default = "35% of classes"
    description = "the number of loaded classes in memory calculation"
    launch = true
    name = "BPL_JVM_LOADED_CLASS_COUNT"

  [[metadata.configurations]]
    default = "250"
    description = "the number of threads in memory calculation"
    launch = true
    name = "BPL_JVM_THREAD_COUNT"

  [[metadata.configurations]]
    default = ""
    description = "write heap dumps on error to this path"
    launch = true
    name = "BPL_HEAP_DUMP_PATH"

  [[metadata.configurations]]
    default = "true"
    description = "enables Java Native Memory Tracking (NMT)"
    launch = true
    name = "BPL_JAVA_NMT_ENABLED"

  [[metadata.configurations]]
    default = "summary"
    description = "configure level of NMT, summary or detail"
    launch = true
    name = "BPL_JAVA_NMT_LEVEL"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Management Extensions (JMX)"
    launch = true
    name = "BPL_JMX_ENABLED"

  [[metadata.configurations]]
    default = "5000"
    description = "configure the JMX port"
    launch = true
    name = "BPL_JMX_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java remote debugging support"
    launch = true
    name = "BPL_DEBUG_ENABLED"

  [[metadata.configurations]]
    default = "8000"
    description = "configure the remote debugging port"
    launch = true
    name = "BPL_DEBUG_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "configure whether to suspend execution until a debugger has attached"
    launch = true
    name = "BPL_DEBUG_SUSPEND"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Flight Recording (JFR)"
    launch = true
    name = "BPL_JFR_ENABLED"

  [[metadata.configurations]]
    default = ""
    description = "configure custom Java Flight Recording (JFR) arguments"
    launch = true
    name = "BPL_JFR_ARGS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "enables running jlink tool to generate custom JRE"
    name = "BP_JVM_JLINK_ENABLED"

  [[metadata.configurations]]
    build = true
    default = "--no-man-pages --no-header-files --strip-debug --compress=1"
    description = "configure custom link arguments (--output must be omitted)"
    name = "BP_JVM_JLINK_ARGS"

  [[metadata.configurations]]
    build = true
    default = "21"
    description = "the Java version"
    name = "BP_JVM_VERSION"

  [[metadata.configurations]]
    build = true
    default = "JRE"
    description = "the JVM type - JDK or JRE"
    name = "BP_JVM_TYPE"

  [[metadata.configurations]]
    description = "the JVM launch flags"
    launch = true
    name = "JAVA_TOOL_OPTIONS"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:1.8.0:update492:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:1.8.0:update492:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@8.0.482?arch=amd64"
    sha256 = "a6d14104f2e7186cba8943c4dc182938db91509dc2c0ef9ecee046c864624d36"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu8.94.0.17-ca-jdk8.0.492-linux_x64.tar.gz"
    version = "8.0.492"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:1.8.0:update502:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:1.8.0:update502:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@8.0.482?arch=amd64"
    sha256 = "1b8ecd86c30177937fb98ce516e28378bb7f01d0eb71b93eb5bfc3153f27cb4e"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu8.96.0.19-ca-jre8.0.502-linux_x64.tar.gz"
    version = "8.0.502"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:11.0.32:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:11.0.32:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@11.0.32?arch=amd64"
    sha256 = "d4832d97886444346ed75fd1059c68c5e38795098e3273e4a0929fe2eb2abf76"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu11.90.19-ca-jdk11.0.32-linux_x64.tar.gz"
    version = "11.0.32"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:11.0.31:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:11.0.31:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@11.0.31?arch=amd64"
    sha256 = "11643d8f13f5af8201b361f8d35fdbc9794c5f6ef98915f5379abb226e5138ab"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu11.88.17-ca-jre11.0.31-linux_x64.tar.gz"
    version = "11.0.31"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:17.0.20:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:17.0.20:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@17.0.20?arch=amd64"
    sha256 = "32c5efedf69f4a95635ea2923f6a6ee90ce6ca83df0bd43ba55dd662d5af429a"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu17.68.17-ca-jdk17.0.20-linux_x64.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:17.0.20:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:17.0.20:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@17.0.20?arch=amd64"
    sha256 = "96c6a5cbc4d0c582bb126d41e280b254db0332a93ed37ae2219debfbe4d3e73f"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu17.68.17-ca-jre17.0.20-linux_x64.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.11:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:21.0.11:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@21.0.11?arch=amd64"
    sha256 = "bc5e3383431cb7f1dce8c262dd474501ee9bd7569f1c59a8b6fe5c1589aa4a58"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu21.50.19-ca-jdk21.0.11-linux_x64.tar.gz"
    version = "21.0.11"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:21.0.12:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:21.0.12:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@21.0.12?arch=amd64"
    sha256 = "8e0374ffe9ff662c2f6b1872d6b48ab3859f69de11afe583af363264d24b299f"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu21.52.15-ca-jre21.0.12-linux_x64.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:25.0.3:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:25.0.3:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@25.0.3?arch=amd64"
    sha256 = "3a93235f4e5b313232647916219e91dc5cca0b9835c9b52a404ba58c43571697"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu25.34.17-ca-jdk25.0.3-linux_x64.tar.gz"
    version = "25.0.3"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:25.0.4:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:25.0.4:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@25.0.4?arch=amd64"
    sha256 = "41540814fa9d5c28d329e4e201c31ee020fc66272b01582c261c5a73d574e80e"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu25.36.15-ca-jre25.0.4-linux_x64.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:26.0.2:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:26.0.2:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@26.0.2?arch=amd64"
    sha256 = "4b7c114917aebd0fc6284fc7111245d7747a4d9603bd12d86b384b1abc9d575d"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu26.32.13-ca-jdk26.0.2-linux_x64.tar.gz"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:26.0.2:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:26.0.2:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@26.0.2?arch=amd64"
    sha256 = "742dc4a5fca3c77a5ea512ad242cdcda364631f46722c84dc4c80390b2b9cbbd"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu26.32.13-ca-jre26.0.2-linux_x64.tar.gz"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:1.8.0:update492:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:1.8.0:update492:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@8.0.482?arch=arm64"
    sha256 = "24f5e8183a52efb5abcee2b8173b0887089ba7476f11bc15603464353cc4e4a8"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu8.94.0.17-ca-jdk8.0.492-linux_aarch64.tar.gz"
    version = "8.0.492"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:1.8.0:update492:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:1.8.0:update492:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@8.0.482?arch=arm64"
    sha256 = "8a8c6d82a36b6564f3ec5472b6ed78c4fe3dd4640ee9be7cb76fd42e7b4463ab"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu8.94.0.17-ca-jre8.0.492-linux_aarch64.tar.gz"
    version = "8.0.492"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:11.0.31:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:11.0.31:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@11.0.31?arch=arm64"
    sha256 = "8fa22d2c45355b7db381f932f8cda60f959299e2836167d79f0ccb3b1465f0fb"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu11.88.17-ca-jdk11.0.31-linux_aarch64.tar.gz"
    version = "11.0.31"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:11.0.31:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:11.0.31:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@11.0.31?arch=arm64"
    sha256 = "a4c081c112b205d4b2a1adfd3fb537500b046455711a29dbc1ddd1fc5e6a6399"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu11.88.17-ca-jre11.0.31-linux_aarch64.tar.gz"
    version = "11.0.31"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:17.0.19:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:17.0.19:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@17.0.19?arch=arm64"
    sha256 = "c17d5657a673c0cfc099e9d803ed30498495894d7359fd1064d463093ed9850b"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu17.66.19-ca-jdk17.0.19-linux_aarch64.tar.gz"
    version = "17.0.19"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:17.0.19:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:17.0.19:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@17.0.19?arch=arm64"
    sha256 = "2921ec4927e3ba5bd970bea3257f236b4235af6640193e999d1a33cba163d6f8"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu17.66.19-ca-jre17.0.19-linux_aarch64.tar.gz"
    version = "17.0.19"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.11:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:21.0.11:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@21.0.11?arch=arm64"
    sha256 = "cd4be5eaed50d2b81485dfe260e2fab7e2c90a854bf11b7bfb4eeb6936757c4a"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu21.50.19-ca-jdk21.0.11-linux_aarch64.tar.gz"
    version = "21.0.11"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:21.0.11:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:21.0.11:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@21.0.11?arch=arm64"
    sha256 = "649464c11d6e8256f0ef6740c84c3401056f6d584efc7c439abeca87a201a9ab"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu21.50.19-ca-jre21.0.11-linux_aarch64.tar.gz"
    version = "21.0.11"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:25.0.3:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:25.0.3:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@25.0.3?arch=arm64"
    sha256 = "2610e5c64df94cee5fb591d70183c5bf8532d8e1d394c754e8ba06751bcceb1b"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu25.34.17-ca-jdk25.0.3-linux_aarch64.tar.gz"
    version = "25.0.3"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:25.0.3:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:25.0.3:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@25.0.3?arch=arm64"
    sha256 = "b2056ebf2431b0ec4f4c4aeb5b839c02ea7df8a90e2fd4d8de86ff8972e8bc53"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu25.34.17-ca-jre25.0.3-linux_aarch64.tar.gz"
    version = "25.0.3"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:26.0.1:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:26.0.1:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "Azul Zulu JDK"
    purl = "pkg:generic/azul-zulu-jdk@26.0.1?arch=arm64"
    sha256 = "cc1b459dc442d7422b46a3b5fe52acaea54879fa7913e29a05650cef54687f5f"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu26.30.11-ca-jdk26.0.1-linux_aarch64.tar.gz"
    version = "26.0.1"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:26.0.1:*:*:*:*:*:*:*", "cpe:2.3:a:azul:zulu:26.0.1:*:*:*:*:*:*:*"]
    id = "jre"
    name = "Azul Zulu JRE"
    purl = "pkg:generic/azul-zulu-jre@26.0.1?arch=arm64"
    sha256 = "bb3efe1c8190eb174beb4d7026edf40dcab5ed7f575f4fa64a1e8f6086cb0561"
    stacks = ["*"]
    uri = "https://cdn.azul.com/zulu/bin/zulu26.30.11-ca-jre26.0.1-linux_aarch64.tar.gz"
    version = "26.0.1"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
